model:
  base_learning_rate: 4.5e-6
  target: taming.models.LG_cvq.VQModel
  params:
    embed_dim: 256
    n_embed: 1024
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0
      drop_prob: 0.1
      clip_text_truncate_len: 30
      mask_transformer_layer: 2
      mask_transformer_head: 1


    lossconfig:
      target: taming.modules.losses.vqperceptual_text.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0
        nceloss_weight: 0.001
        mskloss_weight: 0.01
        wrsloss_weight: 0.0001

dataset:
    target: taming.dataloader.DataModuleFromConfig
    params:
        batch_size: 8
        num_workers: 0
        train:
            target: taming.dataloader.celetext.CelehqTrain
            params:
                root: ./dataset/celehq
                resolution: 256
                clip_text_truncate_len: 30

        validation:
            target: taming.dataloader.celetext.CelehqValidation
            params:
                root: ./dataset/celehq
                resolution: 256
                clip_text_truncate_len: 30

